export default interface Introduction {
    Id?:                         string;
    Name?:                       string;
    CreatedBy?:                  string;
    CreatedDate?:                string;
    Owner_short__c?:             string;
    BD_Owner_Full_Name__c?:      string;
    Account_Name__c?:            string;
    Lost_Communicated__c?:       boolean;
    Interview_Scheduled_for__c?: string;
    Notes__c?:                   string;
    Lion_Full_Name__c?:          string;
    MobilePhone?: string;
    Email?: string;
    Introduction_active__c?: boolean;
    Stage_changed__c?:          string;
    Job__c?:         string;
    Account_Job__c?:        string;
    Date_Lost__c?:       string;
    Stage__c?: string;
    BD_Manager__c?: string;
    Ownership_Filter__c?: string;
    Job_Title__c?: string;
    Account_Id__c?: string;
    Lion__c?: string;
    BD_Manager?: string;
    OwnerId?: string;
    Lion_plus__c?: string;
}